# Form implementation generated from reading ui file 'dandere2x_session_statistics_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SessionStatistics(object):
    def setupUi(self, SessionStatistics):
        SessionStatistics.setObjectName("SessionStatistics")
        SessionStatistics.resize(293, 300)
        self.label = QtWidgets.QLabel(SessionStatistics)
        self.label.setGeometry(QtCore.QRect(10, 10, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SessionStatistics)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(SessionStatistics)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_session_statistics_current_frame = QtWidgets.QLabel(SessionStatistics)
        self.label_session_statistics_current_frame.setGeometry(QtCore.QRect(230, 50, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.label_session_statistics_current_frame.setFont(font)
        self.label_session_statistics_current_frame.setObjectName("label_session_statistics_current_frame")
        self.label_session_statistics_frames_remaining = QtWidgets.QLabel(SessionStatistics)
        self.label_session_statistics_frames_remaining.setGeometry(QtCore.QRect(230, 70, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.label_session_statistics_frames_remaining.setFont(font)
        self.label_session_statistics_frames_remaining.setObjectName("label_session_statistics_frames_remaining")

        self.retranslateUi(SessionStatistics)
        QtCore.QMetaObject.connectSlotsByName(SessionStatistics)

    def retranslateUi(self, SessionStatistics):
        _translate = QtCore.QCoreApplication.translate
        SessionStatistics.setWindowTitle(_translate("SessionStatistics", "Dialog"))
        self.label.setText(_translate("SessionStatistics", "Session Statistics"))
        self.label_2.setText(_translate("SessionStatistics", "Current Frame"))
        self.label_3.setText(_translate("SessionStatistics", "Frames Remaining"))
        self.label_session_statistics_current_frame.setText(_translate("SessionStatistics", "   9999"))
        self.label_session_statistics_frames_remaining.setText(_translate("SessionStatistics", "   9999"))
