# Form implementation generated from reading ui file 'dandere2x_about.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutDandere2x(object):
    def setupUi(self, AboutDandere2x):
        AboutDandere2x.setObjectName("AboutDandere2x")
        AboutDandere2x.resize(385, 588)
        AboutDandere2x.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(AboutDandere2x)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(24, 22, 211, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(20, 64, 343, 507))
        font = QtGui.QFont()
        font.setKerning(True)
        self.textBrowser.setFont(font)
        self.textBrowser.setAutoFillBackground(True)
        self.textBrowser.setObjectName("textBrowser")
        AboutDandere2x.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AboutDandere2x)
        self.statusbar.setObjectName("statusbar")
        AboutDandere2x.setStatusBar(self.statusbar)

        self.retranslateUi(AboutDandere2x)
        QtCore.QMetaObject.connectSlotsByName(AboutDandere2x)

    def retranslateUi(self, AboutDandere2x):
        _translate = QtCore.QCoreApplication.translate
        AboutDandere2x.setWindowTitle(_translate("AboutDandere2x", "About Dandere2x"))
        self.label.setText(_translate("AboutDandere2x", "About Dandere2x"))
        self.textBrowser.setHtml(_translate("AboutDandere2x", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9.13433pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9.13433pt;\">Dandere2x is free open source software </span><span style=\" font-size:9.13433pt; font-style:italic;\">(FOSS for short)</span><span style=\" font-size:9.13433pt;\"> that is developed and maintained by akai-katto. It\'s goal is to make super-resolution a much faster process by implementing a technique known as &quot;lazy upscaling&quot;, which only upscales blocks of pixels (aka block matching) that doesn\'t dramatically change between frames. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9.13433pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9.13433pt;\">Dandere2x is made with much love for the super-resolution community, and although the dandere2x program is designed for anime, appreciates what super-resolution has to offer to the world.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9.13433pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9.13433pt;\">There is no donation link for dandere2x, as I do not intend on making money from this program. If you wish to donate however, you can do so by participating in the following:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9.13433pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9.13433pt;\">1) Uploading your upscaled footage somewhere, such as youtube or vimeo. Videos upscaled by dandere2x has been the primary way dandere2x has grown over the years.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9.13433pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9.13433pt;\">2) Mentioning dandere2x on the internet. Most of dandere2x\'s growth has been users discussing the program at large.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9.13433pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9.13433pt;\">3) Submitting bugs and improvement suggestions. There\'s testing done by 30 users testing my program than I can ever do by myself.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9.13433pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9.13433pt;\">4) Subscribing to or visiting /r/dandere2x. Any show of interest in the program motivates me to continue to maintain the program. </span></p></body></html>"))
