dandere2x_settings:
  block_size: '60'
  multiprocess_thread_count: '2'
  processtype: multiprocess
  quality_coefficient: '100'
  scale_factor: '2'
waifu2x_settings:
  denoise_level: '3'
  model: models-cunet
  tile_size: '50'
  waifu2x_processes: '1'
