name: GitHubActionsBuilds

on: push

jobs:
  generate_version_number:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

  build_windows:
    needs: generate_version_number
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PyInstaller
        run: pip3 install pyinstaller
      - name: Pip install requirements
        run: pip3 install -r src/requirements.txt
      - name: Build to single executable
        run: |
          cd src
          pyinstaller --onefile gui_driver.py
      - name: ls
        run: ls -R
      - uses: actions/upload-artifact@v3
        with:
          name: dandere2x_windows
          path: src/main.exe

